# Generated by Django 5.2.5 on 2025-10-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_product_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickFilter',
        ),
    ]
