# Generated by Django 5.2.5 on 2025-10-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_taggroup_alter_tag_name_tag_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['group_name', 'name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tag',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название группы тегов'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='group',
        ),
        migrations.DeleteModel(
            name='TagGroup',
        ),
    ]
