# Generated by Django 5.2.5 on 2025-10-19 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tag_options_alter_tag_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тег'),
        ),
        migrations.CreateModel(
            name='ProductTagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название группы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_groups', to='api.product', verbose_name='Товар')),
                ('tags', models.ManyToManyField(blank=True, to='api.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Группа тегов товара',
                'verbose_name_plural': 'Группы тегов товара',
            },
        ),
    ]
