# Generated by Django 5.2.5 on 2025-10-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tag_options_remove_tag_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttaggroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' '),
        ),
    ]
