# Generated by Django 5.2.5 on 2025-10-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_producttaggroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
