# Generated by Django 5.2.5 on 2025-10-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttaggroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название тега'),
        ),
    ]
