# Generated by Django 5.2.5 on 2025-10-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_producttaggroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.category', verbose_name='Категория'),
        ),
    ]
