# Generated by Django 5.2.5 on 2025-10-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_feature_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='api.category', verbose_name='Категория'),
        ),
    ]
