# Generated by Django 5.2.5 on 2025-11-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_brand_logo_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productfeature',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='producttaggroup',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producttaggroup_group_name', to='api.tag', verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='producttaggroup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='producttaggroup_tags', to='api.tag', verbose_name='Теги'),
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='value',
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='api.feature', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
                'unique_together': {('feature', 'value')},
            },
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value',
            field=models.ManyToManyField(blank=True, related_name='product_features', to='api.featurevalue', verbose_name='Значение'),
        ),
    ]
