# Generated by Django 5.2.5 on 2025-11-20 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_productfeature_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя тега')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_names', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Имя тега',
                'verbose_name_plural': 'Имена тегов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='producttaggroup',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producttaggroup_group_name', to='api.tagname', verbose_name='Название тега'),
        ),
    ]
