# Generated by Django 5.2.5 on 2025-11-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tagname_alter_producttaggroup_group_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featurevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='featurevalue',
            name='feature',
        ),
        migrations.AlterField(
            model_name='producttaggroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название тега'),
        ),
        migrations.AlterUniqueTogether(
            name='productfeature',
            unique_together={('product', 'feature')},
        ),
        migrations.AlterField(
            model_name='producttaggroup',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag', verbose_name='Теги'),
        ),
        migrations.DeleteModel(
            name='TagName',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='value',
        ),
        migrations.DeleteModel(
            name='FeatureValue',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value',
            field=models.CharField(default=1, max_length=500, verbose_name='Значение'),
            preserve_default=False,
        ),
    ]
