# Generated by Django 5.2.5 on 2025-11-20 18:00

import django.db.models.deletion
from django.db import migrations, models


def clear_productfeature(apps, schema_editor):
    """Очистить данные ProductFeature перед изменением типа поля"""
    ProductFeature = apps.get_model('api', 'ProductFeature')
    ProductFeature.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_producttaggroup_tags_tagname_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_productfeature),
        migrations.AlterUniqueTogether(
            name='productfeature',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='api.feature', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
                'ordering': ['value'],
                'unique_together': {('feature', 'value')},
            },
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='api.featurevalue', verbose_name='Значение'),
        ),
    ]
