# Generated by Django 5.2.5 on 2026-01-05 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_featurevalue_category_nullable_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP manzil')),
                ('reason', models.TextField(blank=True, verbose_name='Sabab')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Bloklangan vaqt')),
            ],
            options={
                'verbose_name': 'Bloklangan IP',
                'verbose_name_plural': 'Bloklangan IPlar',
            },
        ),
        migrations.CreateModel(
            name='AdminLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('user_agent', models.TextField(verbose_name="Brauzer ma'lumoti")),
                ('device_info', models.CharField(blank=True, max_length=500, verbose_name='Qurilma')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('blocked', 'Bloklangan')], default='pending', max_length=20, verbose_name='Holat')),
                ('approval_token', models.CharField(max_length=64, unique=True, verbose_name='Tasdiqlash tokeni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('expires_at', models.DateTimeField(verbose_name='Muddati tugash vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Admin kirish urinishi',
                'verbose_name_plural': 'Admin kirish urinishlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedAdminIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('device_info', models.CharField(blank=True, max_length=500, verbose_name='Qurilma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Oxirgi ishlatilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tasdiqlangan admin IP',
                'verbose_name_plural': 'Tasdiqlangan admin IPlar',
                'unique_together': {('user', 'ip_address')},
            },
        ),
    ]
