# Generated by Django 5.2.5 on 2026-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_blockedip_adminloginattempt_approvedadminip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminloginattempt',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='approvedadminip',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='approvedadminip',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlockedIP',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=25, null=True, verbose_name='Цена'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='api_product_categor_d0689a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'price'], name='api_product_categor_8d8450_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='api_product_brand_i_37891c_idx'),
        ),
        migrations.DeleteModel(
            name='AdminLoginAttempt',
        ),
        migrations.DeleteModel(
            name='ApprovedAdminIP',
        ),
    ]
