# Generated by Django 5.2.5 on 2026-01-07 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_banner_optional_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.tagname', verbose_name='Группа тегов'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'tag_group')},
        ),
    ]
