# Generated by Django 5.2.5 on 2026-01-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_tag_group_to_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagname',
            options={'ordering': ['name'], 'verbose_name': 'Группа тегов', 'verbose_name_plural': 'Группы тегов'},
        ),
        migrations.AddField(
            model_name='feature',
            name='allowed_values',
            field=models.ManyToManyField(blank=True, related_name='allowed_in_features', to='api.featurevalue', verbose_name='Допустимые значения'),
        ),
    ]
