# Generated by Django 5.2.5 on 2026-01-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_allowed_values_to_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagname',
            options={'ordering': ['name'], 'verbose_name': 'Имя тега', 'verbose_name_plural': 'Имена тегов'},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='feature',
            name='allowed_values',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='featurevalue',
            unique_together={('feature', 'value')},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_group',
        ),
    ]
