# Generated by Django 5.2.5 on 2026-01-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_feature_value_feature_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='api.tagname', verbose_name='Группа тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тег'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag_name', 'name')},
        ),
    ]
