# Generated by Django 5.2.5 on 2026-02-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_tag_tag_name_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название характеристики'),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('name', 'category')},
        ),
    ]
