# Generated by Django 5.2.5 on 2026-02-16 09:43

from django.db import migrations, models


def migrate_feature_values(apps, schema_editor):
    """Переносим данные из ForeignKey в ManyToMany"""
    Feature = apps.get_model('api', 'Feature')
    FeatureValue = apps.get_model('api', 'FeatureValue')
    
    # Для каждого значения, привязанного к характеристике, создаем связь ManyToMany
    for value in FeatureValue.objects.filter(feature__isnull=False):
        # Добавляем значение в ManyToMany поле характеристики
        value.feature.values.add(value)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_feature_name_alter_feature_unique_together'),
    ]

    operations = [
        # Шаг 1: Изменяем уникальность FeatureValue
        migrations.AlterUniqueTogether(
            name='featurevalue',
            unique_together={('category', 'value')},
        ),
        # Шаг 2: Добавляем ManyToMany поле
        migrations.AddField(
            model_name='feature',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='features', to='api.featurevalue', verbose_name='Значения'),
        ),
        # Шаг 3: Мигрируем данные
        migrations.RunPython(migrate_feature_values, reverse_code=migrations.RunPython.noop),
        # Шаг 4: Удаляем старое поле
        migrations.RemoveField(
            model_name='featurevalue',
            name='feature',
        ),
    ]
