# Generated by Django 5.2.5 on 2026-05-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_contactinfo_social_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours',
            field=models.CharField(blank=True, default='Пн-Пт: 9:00-18:00', max_length=200, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='image',
            field=models.URLField(blank=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.URLField(blank=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('completed', 'Выполнен'), ('cancelled', 'Отменён'), ('wrong_phone', 'Неправильный номер телефона'), ('no_answer', 'Не поднял трубку')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
