# Generated by Django 5.2.15 on 2026-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_contactinfo_working_hours_alter_aboutcontent_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
    ]
