# Generated by Django 5.2.15 on 2026-07-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_add_customer_telegram_to_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'category')},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='tagname',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя тега'),
        ),
        migrations.AlterUniqueTogether(
            name='tagname',
            unique_together={('name', 'category')},
        ),
    ]
