"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

from config.env import env_bool, env_list, resolve_secret_key

# SECURITY: DEBUG is off unless explicitly enabled (DEBUG=True in the environment).
DEBUG = env_bool('DEBUG', False)

# SECURITY: production refuses to start without its own SECRET_KEY;
# keys that were ever committed to the repository are always rejected.
SECRET_KEY = resolve_secret_key(os.environ, DEBUG)

# Comma-separated list in the ALLOWED_HOSTS environment variable.
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', ['ncb-1.onrender.com'])
if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1']
if os.environ.get('REPLIT_DEV_DOMAIN'):
    ALLOWED_HOSTS.append(os.environ['REPLIT_DEV_DOMAIN'])

# Uploaded media are served by Django itself (no separate media server on Render).
SERVE_MEDIA = env_bool('SERVE_MEDIA', True)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'api',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',  # GZIP сжатие - первым!
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# CORS настройки - только доверенные домены!
# В production убедитесь что здесь только ваши настоящие домены
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "https://nargi.netlify.app",
    "https://ncff.netlify.app",
    "https://ncf-puce.vercel.app",
]

# Add Replit dev domain dynamically
import os as _os
_replit_domain = _os.environ.get('REPLIT_DEV_DOMAIN', '')
if _replit_domain:
    CORS_ALLOWED_ORIGINS += [
        f"https://{_replit_domain}",
        f"http://{_replit_domain}",
    ]

# В production можно ограничить CORS только для production доменов
if not DEBUG:
    CORS_ALLOWED_ORIGINS = [
        origin for origin in CORS_ALLOWED_ORIGINS 
        if origin.startswith('https://')
    ]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
    'pragma',
    'expires',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/hour' if DEBUG else '500/hour',  # Строже в production
        'user': '5000/hour' if DEBUG else '2000/hour',
        'login': '5/hour',  # Защита от брутфорса
    },
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}  # False для JavaScript доступа (API)
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_HTTPONLY = False  # JS needs to read CSRF token for API calls
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "https://nargi.netlify.app",
    "https://ncff.netlify.app",
]

# В production фильтруем только HTTPS
if not DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        origin for origin in CSRF_TRUSTED_ORIGINS 
        if origin.startswith('https://')
    ]

CORS_ALLOW_ALL_ORIGINS = False  # НИКОГДА не ставьте True в production!
CORS_ALLOW_CREDENTIALS = True

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security Settings для Production
if not DEBUG:
    # HTTPS Enforcement
    SECURE_SSL_REDIRECT = True  # Автоматический редирект на HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 year - браузер будет использовать только HTTPS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookie Security
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Защита от MIME-sniffing
    SECURE_BROWSER_XSS_FILTER = True  # Защита от XSS
    
    # Frame Options
    X_FRAME_OPTIONS = 'DENY'  # Защита от clickjacking
    
    # Proxy Settings (для Render/Heroku)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Cookie настройки для production
    SESSION_COOKIE_SECURE = True  # Только HTTPS
    CSRF_COOKIE_SECURE = True  # Только HTTPS
    
    # Дополнительная защита
    SECURE_REFERRER_POLICY = 'same-origin'  # Защита от утечки информации
else:
    # Development settings
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    
# Общие настройки безопасности (всегда активны)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_CONTENT_TYPE_OPTIONS = 'nosniff'

# Ограничение размера загружаемых данных (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Ограничение количества полей в POST запросе (защита от HashDoS)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Session security
SESSION_COOKIE_HTTPONLY = True  # JS не может читать session cookie
SESSION_COOKIE_AGE = 3600  # 1 час
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Password validation - строгая проверка паролей
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Минимум 8 символов
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Logging для отслеживания проблем безопасности
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if DEBUG else 'WARNING',
    },
    'loggers': {
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
